title: hci-prelims
email: "jeremy.warner@berkeley.edu"
description: "HCI prelim study materials"

url: "https://jeremywrnr.com"
baseurl: "/hci-prelims"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
