title: hci reading
email: "jeremy.warner@berkeley.edu"
description: "HCI prelim study and reading materials"

url: "https://jeremywrnr.com"
baseurl: "/hci-prelims"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
