# Site settings
title: prelims
email: ""
description: ""
baseurl: "/hci-prelims"
url: "https://jeremywrnr.com"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
